### ISSUE TITLE
idrop-lite backtrace when trying bulk upload

### ISSUE THREAD

**Issue by brainstorm** [INCF/ids-tools#10]
As reported by a user of DataSpace while trying to upload a bunch of files via `idrop-lite`:

... we might need to upgrade the jar.

```
cedTea-Web Plugin version: 1.5 (1.5-1ubuntu1)
Thu Jun 26 16:47:35 CEST 2014
net.sourceforge.jnlp.LaunchException: Fatal: Initialization Error: Could not initialize applet. For more information click "more information button".
    at net.sourceforge.jnlp.Launcher.createApplet(Launcher.java:746)
    at net.sourceforge.jnlp.Launcher.getApplet(Launcher.java:675)
    at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:908)
Caused by: net.sourceforge.jnlp.LaunchException: Fatal: Initialization Error: Unknown Main-Class. Could not determine the main class for this application.
    at net.sourceforge.jnlp.runtime.JNLPClassLoader.initializeResources(JNLPClassLoader.java:681)
    at net.sourceforge.jnlp.runtime.JNLPClassLoader.<init>(JNLPClassLoader.java:277)
    at net.sourceforge.jnlp.runtime.JNLPClassLoader.createInstance(JNLPClassLoader.java:351)
    at net.sourceforge.jnlp.runtime.JNLPClassLoader.getInstance(JNLPClassLoader.java:418)
    at net.sourceforge.jnlp.runtime.JNLPClassLoader.getInstance(JNLPClassLoader.java:394)
    at net.sourceforge.jnlp.Launcher.createApplet(Launcher.java:711)
    ... 2 more
Caused by: java.lang.ClassNotFoundException: Could not find class org.irods.jargon.idrop.lite.iDropLiteApplet
    at net.sourceforge.jnlp.runtime.JNLPClassLoader$CodeBaseClassLoader.findClassNonRecursive(JNLPClassLoader.java:2483)
    at net.sourceforge.jnlp.runtime.JNLPClassLoader.findClass(JNLPClassLoader.java:1653)
    at net.sourceforge.jnlp.runtime.JNLPClassLoader$CodeBaseClassLoader.findClass(JNLPClassLoader.java:2496)
    at net.sourceforge.jnlp.runtime.JNLPClassLoader.initializeResources(JNLPClassLoader.java:678)
    ... 7 more
Caused by: java.security.PrivilegedActionException: java.lang.ClassNotFoundException: org.irods.jargon.idrop.lite.iDropLiteApplet
    at java.security.AccessController.doPrivileged(Native Method)
    at net.sourceforge.jnlp.runtime.JNLPClassLoader$CodeBaseClassLoader.findClassNonRecursive(JNLPClassLoader.java:2473)
    ... 10 more
Caused by: java.lang.ClassNotFoundException: org.irods.jargon.idrop.lite.iDropLiteApplet
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at net.sourceforge.jnlp.runtime.JNLPClassLoader$CodeBaseClassLoader.access$2001(JNLPClassLoader.java:2445)
    at net.sourceforge.jnlp.runtime.JNLPClassLoader$CodeBaseClassLoader$1.run(JNLPClassLoader.java:2476)
    at net.sourceforge.jnlp.runtime.JNLPClassLoader$CodeBaseClassLoader$1.run(JNLPClassLoader.java:2474)
    ... 12 more

Chain:
1) at Thu Jun 26 16:47:25 CEST 2014
net.sourceforge.jnlp.LaunchException: Fatal: Initialization Error: Unknown Main-Class. Could not determine the main class for this application.
    at net.sourceforge.jnlp.runtime.JNLPClassLoader.initializeResources(JNLPClassLoader.java:681)
    at net.sourceforge.jnlp.runtime.JNLPClassLoader.<init>(JNLPClassLoader.java:277)
    at net.sourceforge.jnlp.runtime.JNLPClassLoader.createInstance(JNLPClassLoader.java:351)
    at net.sourceforge.jnlp.runtime.JNLPClassLoader.getInstance(JNLPClassLoader.java:418)
    at net.sourceforge.jnlp.runtime.JNLPClassLoader.getInstance(JNLPClassLoader.java:394)
    at net.sourceforge.jnlp.Launcher.createApplet(Launcher.java:711)
    at net.sourceforge.jnlp.Launcher.getApplet(Launcher.java:675)
    at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:908)
Caused by: java.lang.ClassNotFoundException: Could not find class org.irods.jargon.idrop.lite.iDropLiteApplet
    at net.sourceforge.jnlp.runtime.JNLPClassLoader$CodeBaseClassLoader.findClassNonRecursive(JNLPClassLoader.java:2483)
    at net.sourceforge.jnlp.runtime.JNLPClassLoader.findClass(JNLPClassLoader.java:1653)
    at net.sourceforge.jnlp.runtime.JNLPClassLoader$CodeBaseClassLoader.findClass(JNLPClassLoader.java:2496)
    at net.sourceforge.jnlp.runtime.JNLPClassLoader.initializeResources(JNLPClassLoader.java:678)
    ... 7 more
Caused by: java.security.PrivilegedActionException: java.lang.ClassNotFoundException: org.irods.jargon.idrop.lite.iDropLiteApplet
    at java.security.AccessController.doPrivileged(Native Method)
    at net.sourceforge.jnlp.runtime.JNLPClassLoader$CodeBaseClassLoader.findClassNonRecursive(JNLPClassLoader.java:2473)
    ... 10 more
Caused by: java.lang.ClassNotFoundException: org.irods.jargon.idrop.lite.iDropLiteApplet
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at net.sourceforge.jnlp.runtime.JNLPClassLoader$CodeBaseClassLoader.access$2001(JNLPClassLoader.java:2445)
    at net.sourceforge.jnlp.runtime.JNLPClassLoader$CodeBaseClassLoader$1.run(JNLPClassLoader.java:2476)
    at net.sourceforge.jnlp.runtime.JNLPClassLoader$CodeBaseClassLoader$1.run(JNLPClassLoader.java:2474)
    ... 12 more
2) at Thu Jun 26 16:47:25 CEST 2014
net.sourceforge.jnlp.LaunchException: Fatal: Initialization Error: Could not initialize applet. For more information click "more information button".
    at net.sourceforge.jnlp.Launcher.createApplet(Launcher.java:746)
    at net.sourceforge.jnlp.Launcher.getApplet(Launcher.java:675)
    at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:908)
Caused by: net.sourceforge.jnlp.LaunchException: Fatal: Initialization Error: Unknown Main-Class. Could not determine the main class for this application.
    at net.sourceforge.jnlp.runtime.JNLPClassLoader.initializeResources(JNLPClassLoader.java:681)
    at net.sourceforge.jnlp.runtime.JNLPClassLoader.<init>(JNLPClassLoader.java:277)
    at net.sourceforge.jnlp.runtime.JNLPClassLoader.createInstance(JNLPClassLoader.java:351)
    at net.sourceforge.jnlp.runtime.JNLPClassLoader.getInstance(JNLPClassLoader.java:418)
    at net.sourceforge.jnlp.runtime.JNLPClassLoader.getInstance(JNLPClassLoader.java:394)
    at net.sourceforge.jnlp.Launcher.createApplet(Launcher.java:711)
    ... 2 more
Caused by: java.lang.ClassNotFoundException: Could not find class org.irods.jargon.idrop.lite.iDropLiteApplet
    at net.sourceforge.jnlp.runtime.JNLPClassLoader$CodeBaseClassLoader.findClassNonRecursive(JNLPClassLoader.java:2483)
    at net.sourceforge.jnlp.runtime.JNLPClassLoader.findClass(JNLPClassLoader.java:1653)
    at net.sourceforge.jnlp.runtime.JNLPClassLoader$CodeBaseClassLoader.findClass(JNLPClassLoader.java:2496)
    at net.sourceforge.jnlp.runtime.JNLPClassLoader.initializeResources(JNLPClassLoader.java:678)
    ... 7 more
Caused by: java.security.PrivilegedActionException: java.lang.ClassNotFoundException: org.irods.jargon.idrop.lite.iDropLiteApplet
    at java.security.AccessController.doPrivileged(Native Method)
    at net.sourceforge.jnlp.runtime.JNLPClassLoader$CodeBaseClassLoader.findClassNonRecursive(JNLPClassLoader.java:2473)
    ... 10 more
Caused by: java.lang.ClassNotFoundException: org.irods.jargon.idrop.lite.iDropLiteApplet
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at net.sourceforge.jnlp.runtime.JNLPClassLoader$CodeBaseClassLoader.access$2001(JNLPClassLoader.java:2445)
    at net.sourceforge.jnlp.runtime.JNLPClassLoader$CodeBaseClassLoader$1.run(JNLPClassLoader.java:2476)
    at net.sourceforge.jnlp.runtime.JNLPClassLoader$CodeBaseClassLoader$1.run(JNLPClassLoader.java:2474)
    ... 12 more
```

**Comment by brainstorm** [comment]
@ganqqwerty, can you try with non-IcedTea versions of Java?

**Comment by brainstorm** [comment]
Tried on OSX with Oracle JAVA, it works. Please report upstream:

https://github.com/DICE-UNC/idrop
